version: "3"
services:
  webserver:
    image: "nestjs/cli"
    volumes:
      - "../.:/home/node"
       # use host's shared memory when running chrome
      - /dev/shm:/dev/shm
    env_file:
      - ~/.docker/.env
    environment:
      - VIRTUAL_HOST=users-sendas.local
    working_dir: "/home/node"
    container_name: users-sendas
    networks:
      - default_local
    command: "tail -f /dev/null"
    ports: 
      - "3000:3000"
networks:
  default_local:
    external: true
